# Generated by Django 2.1.7 on 2019-02-28 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectSputnic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_o', models.CharField(max_length=100)),
                ('name_o', models.CharField(max_length=100)),
                ('rank_o', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RubricSputnic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Sputnic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(blank=True)),
                ('time', models.TimeField(blank=True)),
                ('domain', models.CharField(blank=True, max_length=200)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('route_api', models.CharField(blank=True, max_length=500)),
                ('heading', models.CharField(blank=True, max_length=100)),
                ('date_get', models.DateField(blank=True)),
                ('time_get', models.TimeField(blank=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AlterIndexTogether(
            name='sputnic',
            index_together={('title', 'author', 'description', 'date', 'time', 'domain', 'url')},
        ),
        migrations.AddField(
            model_name='rubricsputnic',
            name='sputnic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_rubrics', to='sputnic.Sputnic'),
        ),
        migrations.AddField(
            model_name='objectsputnic',
            name='sputnic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_objects', to='sputnic.Sputnic'),
        ),
    ]
