# Generated by Django 2.1.7 on 2019-02-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sputnic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sputnic',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sputnic',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
