# Generated by Django 2.1.7 on 2019-02-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sputnic', '0002_auto_20190228_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sputnic',
            name='date_get',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sputnic',
            name='time_get',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
