# Generated by Django 2.1.7 on 2019-02-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sputnic', '0003_auto_20190228_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sputnic',
            name='date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sputnic',
            name='date_get',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sputnic',
            name='time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sputnic',
            name='time_get',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
