# Generated by Django 2.1.7 on 2019-03-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sputnic', '0004_auto_20190228_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sputnic',
            options={'ordering': ['date_get']},
        ),
        migrations.AlterField(
            model_name='sputnic',
            name='date_get',
            field=models.DateField(blank=True),
        ),
    ]
