# Generated by Django 2.1.7 on 2019-03-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sputnic', '0005_auto_20190304_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sputnic',
            name='date_get',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
