# Generated by Django 2.1.7 on 2019-03-04 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sputnic', '0006_auto_20190304_1513'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='sputnic',
            index_together={('title', 'author', 'description', 'date_get', 'time_get', 'domain', 'url')},
        ),
    ]
