# Generated by Django 2.1.7 on 2019-03-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sputnic', '0008_auto_20190305_1318'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sputnic',
            index=models.Index(fields=['title'], name='sputnic_spu_title_b7c253_idx'),
        ),
        migrations.AddIndex(
            model_name='sputnic',
            index=models.Index(fields=['description'], name='sputnic_spu_descrip_ad692f_idx'),
        ),
    ]
