# Generated by Django 2.1.7 on 2019-03-06 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sputnic', '0009_auto_20190305_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sputnic',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='sputnic',
            name='sputnic_spu_title_049aa9_idx',
        ),
        migrations.RemoveIndex(
            model_name='sputnic',
            name='sputnic_spu_title_b7c253_idx',
        ),
        migrations.RemoveIndex(
            model_name='sputnic',
            name='sputnic_spu_descrip_ad692f_idx',
        ),
        migrations.AlterField(
            model_name='sputnic',
            name='description',
            field=models.TextField(blank=True, db_index=True),
        ),
    ]
