# Generated by Django 2.1.7 on 2019-03-06 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sputnic', '0012_auto_20190306_0655'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sputnic',
            name='sputnic_spu_descrip_ad692f_idx',
        ),
    ]
