# Generated by Django 2.1.7 on 2019-03-06 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sputnic', '0015_auto_20190306_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sputnic',
            options={'ordering': ['date_get']},
        ),
    ]
